spring:
  application:
    name: etree-backend
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${DATASOURCE_NAME:}
    password: ${DATASOURCE_PASS:}
    driverClassName: org.postgresql.Driver
openai:
    apiKey: ${API_KEY:}
    org-id: ${OPENAI_ORG_ID:}
    project-id: ${OPENAI_PROJECT_ID:}
